### ISSUE TITLE
Feature idea: flyable ultralight drone (similar to DERP)

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#123]
- Less bulk than DERP
- Fly in 3D, scout targets with camera
- Mark targets or points (projects "holographic" actor object from player while interface is open)
- No weapons
- Drone buzzing noise alerts monsters like DERP does? Or silent anti-grav propulsion?
- Longer signal range

**Comment by VBawss** [comment]
[DeusDoom](https://github.com/cyberc001/deusdoom) does something similar with the Spy Drone augment although there's a small issue with it where the mouse movements are extraordinally limited i.e. instead of moving my mouse 4" to make a full 180° turn I have to move my mouse well over 16" to make a full 180° turn. Either way, it could be a good guideline to draw inspiration from.

**Comment by mc776** [comment]
The noise issue is kinda why I've avoided adding something like this to HD myself - it should be noticeably noisier than the DERP but it wouldn't quite justify constant monster alert calls (and the corresponding taxing of system resources).

Or maybe it could have a gun too, but it's noisier and slower if it has to carry anything...

**Comment by caligari87** [comment]
After more thought I'm not super-invested in this idea.
