### ISSUE TITLE
messkits are not spawned with players and don't seem to spawn on later levels

### ISSUE THREAD

**Issue by infoman-cor** [caligari87/Ugly-as-Sin#128]
Hunger is turned on yet I don't seem to be given a messkit on episode start nor can I find one in future levels.

I might be missing something but from what I can gather the hunger module description implies that you should begin with a messkit. Disregard if this is no longer the case.

**Comment by caligari87** [comment]
This is intentional actually, I probably forgot to update some documentation. The Messkit can (for now) be placed in a loadout with the `msk` code, so the "start with messkit" feature is no longer needed.

HOWEVER

I'm currently deep into refactoring the hunger feature, and the messkit will *possibly* be going away completely in favor of letting you consume most foods directly (alternatively, the messkit might be replaced or repurposed into a "camp stove"-like thing for cooking or otherwise prepping foods, if I get to that point).

You can test the new system on the [hunger_refactor2 branch](https://github.com/caligari87/Ugly-as-Sin/tree/hunger_refactor2), though it's still alpha status and not quite complete.
