### ISSUE TITLE
Certain Advanced AI modules unavailable?

### ISSUE THREAD

**Issue by SlendyOfDaMawn** [caligari87/Ugly-as-Sin#169]
The following _Advanced AI_ modules are greyed out/unavailable and have to be manually changed with cvars:

- Searching
- Stealth

I tried looking around but couldn't find a reason why this would be, is it some compatibility issue or are they disabled due to issues?

_Not even sure changing the cvars even does anything_

**Comment by caligari87** [comment]
Unfortunately they are disabled due to issues with crashes related to AI and other changes in Hideous Destructor (see #161 and #163). This is the commit which made the change: 2e6e6fff7675bd61f4d9021a9f93e0a1c769a59c

Currently I'm taking a break from UaS and HD and focusing on another project, but I hope to get back to these at some point in the future. If you wish to force-enable the features for testing, set `UaS_AI_Debug_Override true` (the cvars will be reset next time the engine is loaded)

**Comment by SlendyOfDaMawn** [comment]
👌
