### ISSUE TITLE
Fragshard reducer mostly non-functional

### ISSUE THREAD

**Issue by Eroc** [caligari87/Ugly-as-Sin#194]
The "Remove Frag" button in the menu works, but the EventHandler doesn't do anything, no matter what the removal rate is set to. Also, at the time of the last change I believe we thought the Archvile curse had been completely removed, but it does actually still exist. It's a thinker called NecromancerGhost now.

**Comment by caligari87** [comment]
Fixed. It was still checking an old cvar that no longer had a menu entry and was set to false by default. If you set the cvar to true manually or had a config where it still existed, the module would work properly.

I don't think I want to neuter the archvile curse with this module, at least not in the same way as frag is handled. I feel that's a separate mechanic. If it worked that way previously, it's because when I wrote this module I didn't realize the curse at that time used invisible fragshards lol.
