### ISSUE TITLE
(Request) Update Wiki

### ISSUE THREAD

**Issue by devlman127** [caligari87/Ugly-as-Sin#238]
The github wiki seems really outdated and incomplete, missing multiple modules and options in the setting. Can you look into updating it?

**Comment by caligari87** [comment]
The wiki is pretty much abandoned at this point and I should just close it.

There is a "manual" which can be accessed from the main README on GitHub, at the following link: https://github.com/caligari87/Ugly-as-Sin/blob/master/manual/contents.md

The contents of this documentation are the individual README files for each module. I've not written all of them yet but it should be more up to date since it lives right next to the code itself.
