### ISSUE TITLE
(Bug) Flashlight visibility settings do nothing

### ISSUE THREAD

**Issue by devlman127** [caligari87/Ugly-as-Sin#239]
Using the Flashlight/Laser module with Flashlight set to visual only still shows the flashlight on when I have the NVG enabled.

**Comment by caligari87** [comment]
I've just tested and this works as intended.

* Visible. This means the flashlight is outputting light in the visible spectrum. Since the NVGs amplify *visible light*, the flashlight is still visible under NVGs
* IR-Only: The flashlight only outputs light in the IR spectrum which is invisible to the naked eye. Since the NVGs are *also* sensitive to IR-spectrum light, the flashlight is only visible under NVG.
